### ISSUE TITLE
Many errors in Hoobs v4

### ISSUE THREAD

**Issue by MikeFumbler** [HommiePeter/homebridge-toon-platform#4]
Happy new year to you all!

I updated Hoobs v3 to Hoobs v4. Big bummer: my whole Apple Homekit network crashed and I was unable to get it running again. I had to do a factory reset and clean install for 60+ devices and many automations...lotsa work.

All fine now, except for Toon Platform bridge. Not working anymore. Apple Home app sees the bridge and accessoiry, but no communication with the Toon unit itself (via the Eneco/Quby servers.

Installed a new token. Reinstalled the plugin, no luck.

What can be wrong?

Log:
1-1-2022 18:31:45Toon Platform BridgeERROR[Toon Platform Bridge 0544@Toon Thermostaat@@Serial Number] [Serial Number] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
1-1-2022 18:31:45Toon Platform BridgeWARNINGunhandled rejection: Error: Requested status but there is no agreement.
1-1-2022 18:31:45Toon Platform BridgeWARNINGunhandled rejection: TypeError: Cannot read properties of undefined (reading 'smokeDetectors')
1-1-2022 18:31:45Toon Platform BridgeWARNINGunhandled rejection: TypeError: Cannot destructure property 'thermostatInfo' of 'this.toon.connection.toonstatus' as it is undefined.

**Comment by HommiePeter** [comment]
Dear Mike 
I developed the plugin for Homebridge. I do not have any experience with Hoobs I will look into it for you, but can not promise you a fast solutions. Maybe using Homebridge instead is workable solution for you ?

**Comment by HommiePeter** [comment]
Dear Mike, 

i tested the new release 0.9.6. (HommiePeter73) with Hoobs and the plugin works. If I look at your logging maybe the token is not correct ?. If your problem still occurs after installing the new release off the plug in please reopen this issue and include the (startup) logging.  

With Kind regards Peter.
