### ISSUE TITLE
Toon API

### ISSUE THREAD

**Issue by Wimterbourne** [HommiePeter/homebridge-toon-platform#6]
Dear sir,

I've registered an application to get an API key, but the callback is not known. What should I set the callback URL to so I can use this plugin?

sincerely,
Wim

**Comment by HommiePeter** [comment]
Dear Wim, 

the Callback URL is not relevant for this plugin. Primairy reason for registration is to get the API key and to be able to login to the Quby API's

With Kind regards,

Peter
